# -*- coding: utf-8 -*-
"""EDA_worl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJ0mgienEA-xuOG_BsvKG11H_4OMl3G4?usp=sharing
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')

# Create outputs folder
os.makedirs('../outputs/plots', exist_ok=True)

# Plot style
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 12
sns.set_theme(style='whitegrid', palette='muted')

# Load cleaned data
df = pd.read_csv('./crop_cleaned.csv')
print('Data loaded. Shape:', df.shape)
df.head()

"""## 1. Yield Distribution"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Raw yield
axes[0].hist(df['Yield'], bins=50, color='steelblue', edgecolor='white', alpha=0.85)
axes[0].set_title('Yield Distribution (Raw)')
axes[0].set_xlabel('Yield (tonnes/hectare)')
axes[0].set_ylabel('Frequency')

# Log yield
axes[1].hist(df['Log_Yield'], bins=50, color='coral', edgecolor='white', alpha=0.85)
axes[1].set_title('Yield Distribution (Log-transformed)')
axes[1].set_xlabel('Log Yield')
axes[1].set_ylabel('Frequency')

plt.tight_layout()
plt.savefig('../outputs/plots/01_yield_distribution.png', dpi=150, bbox_inches='tight')
plt.show()
print('Plot saved: 01_yield_distribution.png')

"""## 2. Top 15 Crops by Average Yield"""

top_crops = df.groupby('Crop')['Yield'].mean().sort_values(ascending=False).head(15).reset_index()

plt.figure(figsize=(14, 6))
bars = plt.barh(top_crops['Crop'], top_crops['Yield'], color=sns.color_palette('viridis', 15))
plt.xlabel('Average Yield (tonnes/hectare)')
plt.title('Top 15 Crops by Average Yield')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('../outputs/plots/02_top_crops_yield.png', dpi=150, bbox_inches='tight')
plt.show()
print('Plot saved: 02_top_crops_yield.png')

"""## 4. Season-wise Average Yield"""

plt.figure(figsize=(12, 6))
season_order = df.groupby('Season')['Yield'].median().sort_values(ascending=False).index
sns.boxplot(data=df, x='Season', y='Yield', order=season_order, palette='Set2')
plt.title('Yield Distribution by Season')
plt.xlabel('Season')
plt.ylabel('Yield (tonnes/hectare)')
plt.xticks(rotation=15)
plt.tight_layout()
plt.savefig('../outputs/plots/04_season_yield_boxplot.png', dpi=150, bbox_inches='tight')
plt.show()
print('Plot saved: 04_season_yield_boxplot.png')



"""## 3. State-wise Average Yield"""

state_yield = df.groupby('State')['Yield'].mean().sort_values(ascending=False).reset_index()

plt.figure(figsize=(16, 7))
sns.barplot(data=state_yield, x='State', y='Yield', palette='coolwarm')
plt.xticks(rotation=60, ha='right', fontsize=9)
plt.title('Average Crop Yield by State')
plt.xlabel('State')
plt.ylabel('Average Yield (tonnes/hectare)')
plt.tight_layout()
plt.savefig('../outputs/plots/03_state_wise_yield.png', dpi=150, bbox_inches='tight')
plt.show()
print('Plot saved: 03_state_wise_yield.png')

year_yield = df.groupby('Crop_Year')['Yield'].mean().reset_index()

plt.figure(figsize=(14, 5))
plt.plot(year_yield['Crop_Year'], year_yield['Yield'], marker='o', color='teal', linewidth=2, markersize=5)
plt.fill_between(year_yield['Crop_Year'], year_yield['Yield'], alpha=0.2, color='teal')
plt.title('Average Crop Yield Trend Over Years')
plt.xlabel('Year')
plt.ylabel('Average Yield (tonnes/hectare)')
plt.tight_layout()
plt.savefig('../outputs/plots/05_year_wise_trend.png', dpi=150, bbox_inches='tight')
plt.show()
print('Plot saved: 05_year_wise_trend.png')



"""## 6. Correlation Heatmap"""

# Select numeric columns for correlation
numeric_cols = ['Crop_Year', 'Area', 'Production', 'Yield', 'Log_Yield', 'Log_Area',
                'State_Encoded', 'Crop_Encoded', 'Season_Encoded']

corr_matrix = df[numeric_cols].corr()

plt.figure(figsize=(12, 8))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            mask=mask, linewidths=0.5, cbar_kws={'shrink': 0.8})
plt.title('Correlation Heatmap — All Features')
plt.tight_layout()
plt.savefig('../outputs/plots/06_correlation_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()
print('Plot saved: 06_correlation_heatmap.png')

"""## 8. Crop Category Summary"""

crop_counts = df['Crop'].value_counts()
print(crop_counts.head(10))
print(f"\nTotal unique crops: {len(crop_counts)}")

"""## 9. Crop Distribution Pie Chart"""

# Take the top 10 crops and sum the rest as 'Other'
top_10_crops = crop_counts.head(10)
other_crops_sum = crop_counts.iloc[10:].sum()

# Create a new series for plotting
pie_data = pd.concat([top_10_crops, pd.Series({'Other': other_crops_sum})])

plt.figure(figsize=(10, 10))
plt.pie(pie_data, labels=pie_data.index, autopct='%1.1f%%', startangle=140, pctdistance=0.85, wedgeprops={'edgecolor': 'white'})
plt.title('Distribution of Crop Categories (Top 10 + Other)')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.tight_layout()
plt.savefig('../outputs/plots/09_crop_distribution_pie_chart.png', dpi=150, bbox_inches='tight')
plt.show()
print('Plot saved: 09_crop_distribution_pie_chart.png')
